[package]
name = "rtfm-app"
version = "0.1.0"
authors = ["Cec√≠lia Carneiro <cecilia.carneiroesilva@gmail.com>"]


[dependencies]
cortex-m = { git = "https://github.com/ceciliacsilva/cortex-m", version = "0.5.7" }
cortex-m-rt = {version = "0.6.4", features = ["device"]} #feature device
cortex-m-rtfm = { git = "https://github.com/ceciliacsilva/cortex-m-rtfm" }


#cortex-m-semihosting = "0.3.1"

#[dependencies.stm32l0]
#version = "0.2.3"
#features = ["stm32l0x1", "rt"]

[dependencies.stm32l052]
version = "0.1.0"
#path = "../../stm32l052"
git = "https://github.com/ceciliacsilva/stm32l052"
features = ["rt"]
